backend/src/Entity/Score.php
<?php

namespace App\Entity;

use App\Repository\ScoreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ScoreRepository::class)]
class Score
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $points = null;

    #[ORM\Column]
    private ?bool $is_local = null;

    #[ORM\ManyToOne(inversedBy: 'scores')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Game $game = null;

    #[ORM\ManyToOne(inversedBy: 'score')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Team $team = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getPoints(): ?int
    {
        return $this->points;
    }

    public function setPoints(?int $points): static
    {
        $this->points = $points;

        return $this;
    }

    public function isIsLocal(): ?bool
    {
        return $this->is_local;
    }

    public function setIsLocal(bool $is_local): static
    {
        $this->is_local = $is_local;

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): static
    {
        $this->game = $game;

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): static
    {
        $this->team = $team;

        return $this;
    }



}

backend/src/Form/ScoreType.php
<?php

namespace App\Form;

use App\Entity\Game;
use App\Entity\Score;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ScoreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('points', null, [
                'label' => 'Points', 
                    'label_attr' => [
                        'class' => 'text-white font-semibold mb-2'
                    ],
                'attr' => [
                    'class' => 'my-4 bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-200 dark:border-gray-600 dark:placeholder-gray-400 dark:text-black dark:focus:ring-blue-500 dark:focus:border-blue-500',
                ],
            ])
            ->add('is_local',null, [
                'label' => 'Is local', 
                'label_attr' => [
                    'class' => 'text-white font-semibold mb-2'
                ],
                'attr' => [
                    'class' => 'my-4 bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block p-2.5 dark:bg-gray-200 dark:border-gray-600 dark:placeholder-gray-400 dark:text-black dark:focus:ring-blue-500 dark:focus:border-blue-500',
                ],
            ])
            ->add('game', EntityType::class, [
                'class' => Game::class,
                'choice_label' => 'id',  
                'label' => 'Game', 
                'label_attr' => [
                    'class' => 'text-white font-semibold mb-2'
                ],
                'attr' => [
                    'class' => 'w-full my-4 bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block p-2.5 dark:bg-gray-200 dark:border-gray-600 dark:placeholder-gray-400 dark:text-black dark:focus:ring-blue-500 dark:focus:border-blue-500',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Score::class,
        ]);
    }
}

backend/src/Controller/ScoreController.php
<?php

namespace App\Controller;

use App\Entity\Score;
use App\Form\ScoreType;
use App\Repository\ScoreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/score')]
class ScoreController extends AbstractController
{
    #[Route('/', name: 'app_score_index', methods: ['GET'])]
    public function index(ScoreRepository $scoreRepository): Response
    {
        return $this->render('score/index.html.twig', [
            'scores' => $scoreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_score_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $score = new Score();
        $form = $this->createForm(ScoreType::class, $score);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($score);
            $entityManager->flush();

            return $this->redirectToRoute('app_score_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('score/new.html.twig', [
            'score' => $score,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_score_show', methods: ['GET'])]
    public function show(Score $score): Response
    {
        return $this->render('score/show.html.twig', [
            'score' => $score,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_score_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Score $score, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ScoreType::class, $score);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_score_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('score/edit.html.twig', [
            'score' => $score,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_score_delete', methods: ['POST'])]
    public function delete(Request $request, Score $score, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$score->getId(), $request->request->get('_token'))) {
            $entityManager->remove($score);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_score_index', [], Response::HTTP_SEE_OTHER);
    }
}

backend/templates/score/_delete_form.html.twig
<form method="post" action="{{ path('app_score_delete', {'id': score.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ score.id) }}">
    
    <button 
        class="w-full bg-red-500 text-white hover:bg-red-600 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">
        Delete
    </button>
</form>

backend/templates/score/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}

<button type="submit"  class=" w-full bg-yellow-400 text-gray-800 hover:bg-yellow-500 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
    {{ button_label|default('Save') }}
</button>

{{ form_end(form) }}

backend/templates/score/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Score{% endblock %}

{% block body %}

<div class="bg-gray-800 text-white p-4 shadow relative">
    <h1 class="text-2xl font-bold text-center my-4 dark:text-white">Editar Puntuación</h1>
    <a href="{{ path('app_score_index') }}" 
       class="absolute top-6 right-4 bg-blue-500 text-white hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-700 dark:hover:bg-blue-800 dark:focus:ring-blue-900">
       Volver a la lista
    </a>
</div>
<div class="flex justify-center items-center min-h-screen bg-gray-100 dark:bg-gray-900">
    <div class="my-6 w-1/3">
        <div class="bg-white rounded-lg shadow-md p-6 dark:bg-gray-800 dark:border-gray-700">
            <h2 class="text-lg font-semibold text-white dark:text-white mb-4">Actualizar Resultado</h2>

            <div class="text-sm font-medium text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-600">  {{ include('score/_form.html.twig', {'button_label': 'Actualizar'}) }}</div>
          {#   <div class="mt-4 flex space-x-4">
                <a href="{{ path('app_score_index') }}" 
                class="bg-blue-500 text-white hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-700 dark:hover:bg-blue-800 dark:focus:ring-blue-900">
                Volver a la lista
                </a>  
            </div> #}
            <div class="mt-4">
            {{ include('score/_delete_form.html.twig') }}
            </div>
            
        </div>
    </div>
</div>
{% endblock %}

backend/templates/score/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Score index{% endblock %}

{% block body %}
<div class="bg-gray-800 text-white p-4 shadow">
    <h1 class="text-2xl font-bold text-center my-4 dark:text-white">Lista de Marcadores</h1>
</div>

<div class="overflow-x-auto my-6">
    <table class="min-w-full bg-white rounded-lg shadow-md dark:bg-gray-800">
        <thead>
            <tr>
                <th class="px-6 py-3 text-left text-sm font-medium text-gray-500 uppercase tracking-wider dark:text-gray-300">
                    ID
                </th>
                <th class="px-6 py-3 text-left text-sm font-medium text-gray-500 uppercase tracking-wider dark:text-gray-300">
                    Puntos
                </th>
                <th class="px-6 py-3 text-left text-sm font-medium text-gray-500 uppercase tracking-wider dark:text-gray-300">
                    Es Local
                </th>
                <th class="px-6 py-3 text-left text-sm font-medium text-gray-500 uppercase tracking-wider dark:text-gray-300">
                    Acciones
                </th>
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200 dark:bg-gray-800 dark:divide-gray-700">
            {% for score in scores %}
                <tr>
                    <td class="px-6 py-4 text-sm font-medium text-gray-900 dark:text-white">
                        {{ score.id }}
                    </td>
                    <td class="px-6 py-4 text-sm text-gray-500 dark:text-gray-400">
                        {{ score.points }}
                    </td>
                    <td class="px-6 py-4 text-sm text-gray-500 dark:text-gray-400">
                        {{ score.isLocal ? 'Sí' : 'No' }}
                    </td>
                    <td class="px-6 py-4 text-sm flex space-x-4">
                        <a href="{{ path('app_score_show', {'id': score.id}) }}" 
                           class="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-600">
                            Ver detalles
                        </a>
                        <a href="{{ path('app_score_edit', {'id': score.id}) }}" 
                           class="text-yellow-500 hover:text-yellow-700 dark:text-yellow-400 dark:hover:text-yellow-600">
                            Editar
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4" class="px-6 py-4 text-center text-sm text-gray-500 dark:text-gray-400">
                        No se encontraron registros.
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="mt-6 flex justify-center">
    <a href="{{ path('app_score_new') }}" 
       class="ml-4 bg-blue-500 text-white hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-700 dark:hover:bg-blue-800 dark:focus:ring-blue-900">
        Crear Nuevo Marcador
    </a>
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('dashboard_admin') }}" 
           class="ml-4 bg-yellow-400 text-gray-800 hover:bg-yellow-500 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-yellow-600 dark:hover:bg-yellow-700 dark:focus:ring-yellow-800">
            Volver al Dashboard
        </a>
    {% elseif is_granted('ROLE_USER') %}
        <a href="{{ path('dashboard_user') }}" 
           class="ml-4 bg-yellow-400 text-gray-800 hover:bg-yellow-500 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-yellow-600 dark:hover:bg-yellow-700 dark:focus:ring-yellow-800">
            Volver al Dashboard
        </a>
    {% endif %}
</div>
{% endblock %}

backend/templates/score/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Score{% endblock %}

{% block body %}
<div class="w-full flex justify-center my-6">
    <div class="w-1/3 bg-white rounded-lg shadow-md p-6 dark:bg-gray-800 dark:border-gray-700">
        <h1 
        class="text-2xl font-bold text-center text-gray-800 dark:text-white mb-4">Create new Score</h1>

        {{ include('score/_form.html.twig') }}

        <div class="mt-4 flex justify-between">
            <a href="{{ path('app_score_index') }}" 
               class="bg-blue-500 text-white hover:bg-blue-600 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-700 dark:hover:bg-blue-800 dark:focus:ring-blue-900">
               Back to list
            </a>
        </div>
    </div>
</div>
{% endblock %}

backend/templates/score/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Score{% endblock %}

{% block body %}
<div class="flex justify-center items-center min-h-screen bg-gray-100 dark:bg-gray-900">
    <div class="bg-white dark:bg-gray-800 shadow-lg rounded-lg p-6 w-full max-w-md">
        <h1 class="text-2xl font-bold text-gray-800 dark:text-white mb-4">Detalles del Puntaje</h1>
        <div class="space-y-4">
            <div class="flex justify-between">
                <span class="font-medium text-gray-700 dark:text-gray-400">Id:</span>
                <span class="text-gray-900 dark:text-white">{{ score.id }}</span>
            </div>
            <div class="flex justify-between">
                <span class="font-medium text-gray-700 dark:text-gray-400">Puntos:</span>
                <span class="text-gray-900 dark:text-white">{{ score.points }}</span>
            </div>
            <div class="flex justify-between">
                <span class="font-medium text-gray-700 dark:text-gray-400">Es local:</span>
                <span class="text-gray-900 dark:text-white">{{ score.isLocal ? 'Sí' : 'No' }}</span>
            </div>
        </div>
        <div class="mt-6 flex justify-between">
            <a href="{{ path('app_score_index') }}" 
               class="bg-blue-500 text-white hover:bg-blue-600 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Volver a la lista
            </a>
            <a href="{{ path('app_score_edit', {'id': score.id}) }}" 
               class="bg-yellow-500 text-white hover:bg-yellow-600 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-yellow-600 dark:hover:bg-yellow-700 dark:focus:ring-yellow-800">
                Editar
            </a>
        </div>
        <div class="mt-4">
            {{ include('score/_delete_form.html.twig') }}
        </div>
    </div>
</div>
{% endblock %}